name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --build-arg GIT_COMMIT=$(git rev-parse --short HEAD) -t app_image .
    - name: Docker compose
      run: docker-compose up -d
    - name: test Version
      run: curl localhost:5000/healthz
      
    
    
